### ISSUE TITLE
Realizzazione di sistemi e funzioni di trasferimento

### ISSUE THREAD

**Issue by espositocloud** [michelesr/dsp_notes#1]
Si potrebbero aggiungere info su:
- Cascata (DONE)
- Parallelo (DONE)
- Schema a blocchi, realizzazione diretta seconda (DONE)
- Scomposizione in tratti semplici (DONE)
- Realizzazione a traliccio-scala (DONE)
- Long division (DONE)
- Residui (DONE)
- Poli e zeri/radici dei polinomi (DONE)
- Stabilita' BIBO (DONE)

Con esempi di Octave dove possibile

**Comment by michelesr** [comment]
Per ora preferisco concentrarmi sulla parte teorica, se vuoi farlo tu @kobe25 son contento!

**Comment by espositocloud** [comment]
Introdotta sezione "Funzioni di trasferimento" con 675a0f5

**Comment by espositocloud** [comment]
Integrata la pagina relativa alle "fratte parziali" in 635ab2da

**Comment by espositocloud** [comment]
Con il traliccio scala chiudiamo, gli esempi con Octave passano..
