### ISSUE TITLE
Indici pari sui W nello stadio 2 delle FFT

### ISSUE THREAD

**Issue by michelesr** [michelesr/dsp_notes#13]
Nei disegni che abbiamo aggiunto alla spiegazione delle `fft` in decimazione del tempo e della frequenza appaiono `W0` e `W2` al secondo stadio (quello centrale) piuttosto che `W0` e `W1` come dovrebbe essere dalla formula e come è negli appunti del prof.

Le sezioni sono:
[Decimazione nel tempo](https://github.com/michelesr/dsp_notes/blob/master/fft.md#decimazione-nel-tempo)
[Decimazione nella frequenza](https://github.com/michelesr/dsp_notes/blob/master/fft.md#decimazione-nella-frequenza)

Io e @kobe25 abbiamo notato molti disegni con la stessa caratteristica su internet, e non sappiamo spiegarci il perchè.

**Comment by michelesr** [comment]
Nel libro Mitra abbiamo `W0` e `W2`.

**Comment by espositocloud** [comment]
Allora andrei su `W0` e `W2`, tanto non e' l'unica cosa non del tutto chiara  :+1:
