### ISSUE TITLE
Modelli di colore

### ISSUE THREAD

**Issue by michelesr** [michelesr/dsp_notes#15]
RGB HSI YMCK ecc...

**Comment by espositocloud** [comment]
Introdotto con 8573a1e8

**Comment by espositocloud** [comment]
Ho aggiunto anche qualcosina su CIELAB visto che lo citava nelle slide.  Si potrebbero mettere delle immagini di esempio ma per me non sono particolarmente significative.

Se per te non c'e' altro da dire chiudi pure.

**Comment by espositocloud** [comment]
Aggiornamento:  le modifiche sono state sovrascritte, attendiamo fix del #16 prima di chiudere questo
