### ISSUE TITLE
[Immagini] - Filtraggio

### ISSUE THREAD

**Issue by espositocloud** [michelesr/dsp_notes#2]
- filtraggio immagini nel dominio delle frequenze
- altro..

**Comment by michelesr** [comment]
Magari potrei metterci mano, dato che la parte sulle immagini è un po' il mio tallone d'achille, imparerò con la pratica...

**Comment by michelesr** [comment]
Aggiunto, anche se qualche immagine esplicativa non sarebbe male (naturalmente non posso prendere quelle del libro dato che c'e' il copyright) :-)

**Comment by michelesr** [comment]
Dai alla fine si capisce anche senza immagini... chiuso!
