### ISSUE TITLE
Poli e zeri per i filtri

### ISSUE THREAD

**Issue by michelesr** [michelesr/dsp_notes#5]
Che significa questo? Si può spiegare meglio?

https://github.com/michelesr/dsp_notes/blob/master/phase.md#poli-e-zeri

Non è molto chiaro quando parla di avvicinare i poli al circolo di raggio unitario PER LE frequenze che si vogliono esaltare (che significa che lo avvicini solo per alcune frequenze? i poli non sono valori fissi?)

**Comment by espositocloud** [comment]
IMHO a seconda del tipo di effetto che vuoi ottenere, modifichi il filtro cambiando i poli (e/o gli zeri)

**Comment by michelesr** [comment]
Risolto... chiudo!
