### ISSUE TITLE
Teoremi vari (Parseval, Nyquist-Shannon...)

### ISSUE THREAD

**Issue by espositocloud** [michelesr/dsp_notes#6]
Potrebbe chiederli?

**Comment by michelesr** [comment]
Hmm... mi sembra un po' generica come domanda, ma non si sa mai... cmq non son complicati

**Comment by espositocloud** [comment]
Ok, li puoi inserire in una pagina `theorems.md`?

**Comment by michelesr** [comment]
Aggiunto Nyquist in 3a63c0d048ee9106ab96514c1d3fc43e4bc3ff48 , pero' ho dei dubbi sulle formule e devo ricontrollarle.

**Comment by michelesr** [comment]
CVD, formula corretta in e4e0f6e9fb64ecd1b154a095f16779affcc2bb5c , aggiunti esempi

**Comment by michelesr** [comment]
Chiudo
