### ISSUE TITLE
Spettro periodico?

### ISSUE THREAD

**Issue by michelesr** [michelesr/dsp_notes#7]
Lo spettro di solito viene valutato tramite FFT su una sequenza di durata L, che coincide con la DTFT campionata su L punti equidistanziati nell'intervallo [0, 2pi].

Però nei grafici vediamo sempre [-pi, +pi] come intervalli, e in quelli in frequenza reale (non angolare) abbiamo [-0.5, 0.5] ... 

Questo è quello che dice il prof, ma di base la DTFT e DFT dovrebbero essere periodiche di periodo 2pi, quindi probabilmente non dovrebbe esserci nessuna differenza tra l'intervallo [-pi, 0] e l'intervallo [pi, 2pi]... 

Sta cosa riesci a confermarmela @kobe25 ?

**Comment by espositocloud** [comment]
Ci penso 2moro  :)

**Comment by espositocloud** [comment]
Yes, mi torna, anche se non capisco perche' ti sei posto questo problema  :)
